baseURL = "https://johnmccabe.github.io"
disablePathToLower = true
title = "johnmccabe.net"
languageCode = "en-us"
theme = "hugo-theme-m10c"
paginate = 15

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

[params]
  author = "John Doe"
  avatar = "/assets/avatar.jpg"
  description = "Belfast based geek. Security Stress Nexus."
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/johnmccabe"
  [[params.social]]
    icon = "mastodon"
    name = "Mastodon"
    url = "https://mastodon.social/@mccabe"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/mccabejohn"

  # Default theme
  #[params.style]
  #  darkestColor = "#242930"
  #  darkColor = "#353b43"
  #  lightColor = "#afbac4"
  #  lightestColor = "#ffffff"
  #  primaryColor = "#57cc8a"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"
  #  primaryColor = "#dad865"

  # Red theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  lightColor = "#d6d6d6"
  #  lightestColor = "#d3d3d3"
  #  primaryColor = "#ffffff"